[features]
seeds = false
skip-lint = false

[programs.localnet]
user_program = "UserPrgm11111111111111111111111111111111111"
poll_program = "Po11CrtrPrgm1111111111111111111111111111111"
vote_program = "VotePrgm11111111111111111111111111111111111"
settlement_program = "Sett1ePrgm1111111111111111111111111111111111"

[programs.devnet]
user_program = "UserPrgm11111111111111111111111111111111111"
poll_program = "Po11CrtrPrgm1111111111111111111111111111111"
vote_program = "VotePrgm11111111111111111111111111111111111"
settlement_program = "Sett1ePrgm1111111111111111111111111111111111"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
